version: '3.5'
services:
    zabbix-server:
        image: zabbix/zabbix-server-mysql:ubuntu-6.2-latest
        ports:
         - "10051:10051"      
        secrets:
         - MYSQL_USER
         - MYSQL_PASSWORD
         - MYSQL_ROOT_USER
         - MYSQL_ROOT_PASSWORD

  
    mysql-server:
        image: mysql:8.0-oracle
        command:
         - mysqld
         - --character-set-server=utf8mb4
         - --collation-server=utf8mb4_bin
         - --default-authentication-plugin=mysql_native_password
        env_file:
         - zabbix_code/env_vars/.env_db_mysql
        secrets:
         - MYSQL_USER
         - MYSQL_PASSWORD
         - MYSQL_ROOT_PASSWORD

    zabbix-web-nginx-mysql:
        image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.2-latest
        ports:
         - "80:8080"
        env_file:
         - zabbix_code/env_vars/.env_db_mysql
         - zabbix_code/env_vars/.env_web
        secrets:
         - MYSQL_USER
         - MYSQL_PASSWORD
        depends_on:
         - mysql-server
         - zabbix-server

secrets:
  MYSQL_USER:
    file: zabbix_code/env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: zabbix_code/env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: zabbix_code/env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: zabbix_code/env_vars/.MYSQL_ROOT_PASSWORD
